travis:
  secure:
    BINSTAR_TOKEN: zukpP20NVxv8UJruXpK83gU5dOosCino0inIv+scNU46scCrQe2EWuIr/CsfqxPOzoC+WBOzjRGFARjJET3iLfinbxH9R9Pd0JHAqRnBonvUX/ePpqqbMuqrf5CEsyJofEB8ViovZ0laXqGBxbafeBVjj1VMZdswa5Hhw7yMr8qiTWwEFkY14IOOmAQpEHWc/y2ujKGeHnWr68cQPhi7t1HtrhNlzyyJ+9uQx+91MSZ1Mm3NeVcGLr7OOZpvhF8DzDbBwpM0Hf0tlIx/IJ8IoA7JIfd0Fh2vHiYb4tn7FkWxJqcNR9TGj9qoqB6IegeVGtQH3oTppswJUXH3+Csi4l/bQZtrblEksAGqzE3RiQFsTCbctGQcoXq9U7cPLm1e+vyKkg5VFLu3YqSS/tp5rer1vVwDblZ+3esS1dU7cknjjwslVKRvNq+rwFzQ4RfNslfIK0GLXUejNGKRyQc1XkGEpz69/o+w5myniFJlaGvSN0HWM1cDe/DF473RDcgc0Owq8XHeqbXFVYonsgEdMyifT5FqrQlGJUMAA2nGXsAij9wAi4tq4uMegicTzED6Kec1rEOtTp5xOWWAzc1CWeUyykhECTWHvzAoYlkhEstisK3/jKd0SprZKeGXV69DlidWxM1zwhd3BnRfoQlxK99J/nuoNy2PyfguOo7L6Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
