travis:
  secure:
    BINSTAR_TOKEN: eAit9+eWt/iTpKK3dgsgUlv3KULeaK48EjACr1DD1psoc0sPBJ8kqWI/HZc2k4g41G9mAQnf6B7vvMpeBrI/tDKdEKaaHPeFq5vh0TRcUyujC5L4HrFu6WZQkPbIztOCyN2V6CxFiUkhNfZxVr15K9Bbn/45NiCp/yYP+YP7xVdgLoqCtqsv5sN3DhYJzO8XIf34bJXorK/NlG5RFIiLOoVfsoKejMu+gOmtcqklXIuTVtao8ZwRnd7zRl0ocfrfD45qpBQ7V6lXmeJTvxfCuBiBEY9NFdM3fdP7OhwGLgq76pvjX9kM19vYwmzHNiVcj+jpir/oDbg+z+YPTeLY9MHM702a1BgyXsDFFjJQbpwE/sIbJ3cF2tsRedtC3TlAF5zKKXFNhUSH9mhpOTlfMo85b+Lg5/z09GRcWHfuLW4f0GrcQBngmlOpSCSwkUIZTBXVOcopBrf5ztUtms2LbaB1HKLqKoBZh6yN9OWISc2EYfsG2dqzW3xCraYVCqNiGFcazPkSF7CBrOcZJ9w2O3ndshy38NIdpJNpRWrJd1KbyrWPXnZiIZf6OCQ5QiuWpEB6W1P19mWJpg9MK+ohcZnOSopub2QOoGzEvJ4WCe9V4S4Ty6wgAR+rEGy1k9MN0AfB4JCM2/SIdZKI4vLxJpWIO1hp9tYkGOgDVnQ88kY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
